### ISSUE TITLE
angular 

### ISSUE THREAD

**Issue by HosseinAfsharnia** [POEC-DOTNET-CLERMONT-2022/ProjetStock#33]
The Angular and its corresponding services.

**Comment by tristanblc** [comment]
ok chef

**Comment by tristanblc** [comment]
@HosseinAfsharnia  I initialize the angular project to create administrator web client interface.
I create an new branch named "feature/website".  If you want to code, please " git pull" it;
Best regards

**Comment by HosseinAfsharnia** [comment]
@tristanblc Thanks for the initiation. I will do as you sugggest.
bests.

**Comment by tristanblc** [comment]
@HosseinAfsharnia can you initiate angular projecr?
I can't work on my pc

**Comment by tristanblc** [comment]
@HosseinAfsharnia now, Angular works. I do and add the project on git.(on branch  feature/website)
Best regards

**Comment by tristanblc** [comment]
@HosseinAfsharnia add et modify works
Git pull if you want code.

**Comment by tristanblc** [comment]
@HosseinAfsharnia now, you have to do your part ; )
