### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by nicolas63** [POEC-DOTNET-CLERMONT-2022/ProjetStock#5]
@tristanblc je vois que ça bosse ! C'est top ! 
Regarde ce qu'est un gitignore et comment le mettre en place pour un environnement dotnet. (Un peu d'aide ici https://www.toptal.com/developers/gitignore)

**Comment by tristanblc** [comment]
Oui, je vais regarder.
Merci pour l'aide.

**Comment by nicolas63** [comment]
De rien, si jamais tu veux une revue de code hésite pas à faire une issue comme je viens de faire et de me notifier dessus

**Comment by tristanblc** [comment]
Je n'hésiterai pas à vous demander.

**Comment by tristanblc** [comment]
Je ne savais pas que sur visual studio qu'il y avait git

**Comment by HosseinAfsharnia** [comment]
Merci @nicolas63. 
Je pense que nous devrions utiliser la partie git de Visual Studio pour le push direct et dans ce cas, nous devions utiliser gitignore pour les objets qu'il produit. Cependant, pour le moment, on push la partie que l'on change dans le code via le terminal (répertoire de notre code).

**Comment by tristanblc** [comment]
@nicolas63
Bonjour,
J'ai une question à te poser. Est ce possible de me répondre , svp?
J'aimerais pouvoir mettre une visibilité comme internal pour l'ensemble de mes classes. J'aimerais que les classes soient accessibles pour mes projets dans ma solution mais pas l'extérieur ( un genre de internal pour une solution).
Et, j'aimerais savoir aussi quand nous allons étudier les bases de données.
Je te remercie d'avance 
Cordialement
